// Shared data: the planning-side dispatch-pin table.
//
// This table used to live inline in planning-role-dispatch-pins.test.mjs. It
// was moved here (apra-fleet-3swo.28 AC#5) so execution-role-dispatch-pins.
// test.mjs can read PLANNING_LADDERS.length to derive the total agent() site
// count without hard-coding a literal that the dispatchRole migration is
// guaranteed to invalidate as ladders move out of runner.js.
//
// This file is PURE DATA -- no functions, no SRC-scanning, no test()/
// describe() calls -- so importing it from a second test file does not
// re-execute planning-role-dispatch-pins.test.mjs's tests a second time.
export const PLANNING_LADDERS = [
    {
        ladder: 'planner',
        name: 'planner (interactive)',
        anchor: '(plannerPrompt,',
        member: "getMemberForRole('planner')",
        agentType: "'planner'",
        modelTier: 'FIXED_ROLE_TIER.planner',
        maxTurns: 500,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: 'true',
        watchdog: true,
        watchdogLabel: "'Plan (interactive)'",
        schema: null,
        resume: "roundSessions.resumeArgFor('planner', cycle)",
    },
    {
        ladder: 'planner',
        name: 'planner (resume after max_turns exhaustion)',
        anchor: 'Continue your planning pass exactly where you left off',
        member: "getMemberForRole('planner')",
        agentType: "'planner'",
        modelTier: 'FIXED_ROLE_TIER.planner',
        maxTurns: 1000,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: 'true',
        watchdog: true,
        watchdogLabel: '`Plan (resume, max_turns=${PLANNER_MAX_TURNS * 2})`',
        schema: null,
        resume: 'true',
    },
    {
        ladder: 'plan-reviewer',
        name: 'plan-reviewer (once)',
        anchor: 'priorRoundVerdicts: priorPlanRoundVerdicts',
        member: "getMemberForRole('plan-reviewer')",
        agentType: "'plan-reviewer'",
        modelTier: "FIXED_ROLE_TIER['plan-reviewer']",
        maxTurns: 500,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: null,
        watchdog: false,
        schema: 'planReviewerVerdict',
        resume: null,
    },
    {
        ladder: 'plan-reviewer',
        name: 'plan-reviewer (resume after max_turns exhaustion)',
        anchor: 'Continue your plan review exactly where you left off',
        member: "getMemberForRole('plan-reviewer')",
        agentType: "'plan-reviewer'",
        modelTier: "FIXED_ROLE_TIER['plan-reviewer']",
        maxTurns: 1000,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: null,
        watchdog: false,
        schema: 'planReviewerVerdict',
        resume: 'true',
    },
    {
        ladder: 'scoped-replan-planner',
        name: 'scoped replan planner',
        anchor: "label: 'Scoped Replan Plan (interactive)'",
        member: "getMemberForRole('planner')",
        agentType: "'planner'",
        modelTier: 'FIXED_ROLE_TIER.planner',
        maxTurns: 500,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: 'true',
        watchdog: true,
        watchdogLabel: "'Scoped Replan Plan (interactive)'",
        schema: null,
        resume: null,
    },
    {
        ladder: 'scoped-replan-plan-reviewer',
        name: 'scoped replan plan-reviewer',
        anchor: "label: 'Scoped Replan Review'",
        member: "getMemberForRole('plan-reviewer')",
        agentType: "'plan-reviewer'",
        modelTier: "FIXED_ROLE_TIER['plan-reviewer']",
        maxTurns: 500,
        timeoutS: 'DISPATCH_TIMEOUT_S',
        maxTotalS: 'DISPATCH_TIMEOUT_S',
        bracketed: true,
        pushCode: 'false',
        pushBeads: null,
        watchdog: false,
        schema: 'planReviewerVerdict',
        resume: null,
    },
    {
        ladder: 'streak-assignment',
        name: 'streak assignment',
        anchor: "label: 'Streak Assignment',",
        member: "getMemberForRole('planner')",
        agentType: null,
        modelTier: 'FIXED_ROLE_TIER.streakAssignment',
        maxTurns: null,
        timeoutS: null,
        maxTotalS: null,
        bracketed: false,
        pushCode: null,
        pushBeads: null,
        watchdog: false,
        schema: 'streakAssignment',
        resume: null,
    },
    {
        ladder: 'streak-assignment',
        name: 'streak assignment (semantic repair re-ask)',
        anchor: "label: 'Streak Assignment (semantic repair)'",
        member: "getMemberForRole('planner')",
        agentType: null,
        modelTier: 'FIXED_ROLE_TIER.streakAssignment',
        maxTurns: null,
        timeoutS: null,
        maxTotalS: null,
        bracketed: false,
        pushCode: null,
        pushBeads: null,
        watchdog: false,
        schema: 'streakAssignment',
        resume: null,
    },
];
