#!/usr/bin/env node
/**
 * build-sea.mjs — esbuild CJS bundle for Node.js SEA
 *
 * Bundles src/ into a single dist/sea-bundle.cjs with:
 * - BUILD_VERSION injected at compile time
 * - import.meta.url shimmed for CJS compat
 * - ssh2's cpu-features native addon marked external
 */

import { build } from 'esbuild';
import { readFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// Read version
const versionFile = JSON.parse(readFileSync(join(root, 'version.json'), 'utf-8'));
let gitHash = '';
try {
  gitHash = execSync('git rev-parse --short=6 HEAD', { cwd: root, encoding: 'utf-8' }).trim();
} catch { /* no git */ }
const version = gitHash ? `v${versionFile.version}_${gitHash}` : `v${versionFile.version}`;

console.log(`Building SEA bundle — version: ${version}`);

await build({
  entryPoints: [join(root, 'src', 'index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  outfile: join(root, 'dist', 'sea-bundle.cjs'),
  sourcemap: false,
  minify: false, // keep readable for debugging
  // Inject BUILD_VERSION at compile time; shim import.meta.url → CJS equivalent
  define: {
    'BUILD_VERSION': JSON.stringify(version),
    'import.meta.url': 'import_meta_url',
  },
  banner: {
    js: [
      '// Node.js SEA bundle — generated by build-sea.mjs',
      'var import_meta_url = typeof document === "undefined" ? require("url").pathToFileURL(__filename).href : undefined;',
    ].join('\n'),
  },
  // ssh2's optional native addon — safe to externalize because ssh2 wraps
  // require('cpu-features') in try/catch (lib/protocol/constants.js:6-8)
  external: ['cpu-features'],
  loader: { '.node': 'empty' },
  // Log size
  metafile: true,
});

console.log(`Bundle written to dist/sea-bundle.cjs`);
