import { z } from 'zod';
import fs from 'node:fs';
import path from 'node:path';
import { removeAgent as removeFromRegistry, getAllAgents, getKeysDir } from '../services/registry.js';
import { getStrategy } from '../services/strategy.js';
import { getOsCommands } from '../os/index.js';
import { wrapPowerShellEncoded } from '../os/windows.js';
import { escapeShellArgInner, escapeSedBasicRegex, escapePowerShellArgInner } from '../utils/shell-escape.js';
import { getProvider } from '../providers/index.js';
import { getAgentOS, getAgentShell } from '../utils/agent-helpers.js';
import { memberIdentifier, resolveMember } from '../utils/resolve-member.js';
import { memberHeldCheck } from './member-owner.js';
import { removeKnownHost } from '../services/known-hosts.js';
import { writeStatusline, readMemberStatus } from '../services/statusline.js';
import { cancelCredentialCleanup } from '../services/credential-cleanup.js';
import { getStallDetector } from '../services/stall/index.js';
import { removeAgyProject } from '../services/agy-project.js';
import { githubProvider } from '../services/vcs/github.js';
import { bitbucketProvider } from '../services/vcs/bitbucket.js';
import { azureDevOpsProvider } from '../services/vcs/azure-devops.js';
import type { Agent } from '../types.js';
import type { VcsProviderService } from '../services/vcs/types.js';
import { logLine } from '../utils/log-helpers.js';
import { removeMemberFromOwnInstall, getMemberFleetMcpDeps } from '../services/member-fleet-install.js';
import { invalidatePreflightCache } from '../services/preflight-check.js';
import { removeComposedMemberConfig } from './compose-permissions.js';

const vcsProviders: Record<string, VcsProviderService> = {
  github: githubProvider,
  bitbucket: bitbucketProvider,
  'azure-devops': azureDevOpsProvider,
};

export const removeMemberSchema = z.object({
  ...memberIdentifier,
  force: z.boolean().optional().default(false).describe(
    'Remove even if the member is currently busy, or if it is held (reservedBy set, or a '
    + 'registered workflow package reports the member held).'
  ),
});

export type RemoveMemberInput = z.infer<typeof removeMemberSchema>;

// Only keys generated by the fleet (setup_ssh_key, under the fleet keys dir)
// may be deleted locally or revoked from the member's authorized_keys. A
// user-supplied key_path (e.g. ~/.ssh/id_ed25519) is never touched.
function isFleetManagedKey(keyPath: string): boolean {
  const keysDir = path.resolve(getKeysDir()) + path.sep;
  const resolved = path.resolve(keyPath);
  return process.platform === 'win32'
    ? resolved.toLowerCase().startsWith(keysDir.toLowerCase())
    : resolved.startsWith(keysDir);
}

export async function removeMember(input: RemoveMemberInput): Promise<string> {
  const agentOrError = resolveMember(input.member_id, input.member_name);
  if (typeof agentOrError === 'string') return agentOrError;
  const agent = agentOrError as Agent;

  // Idle check: block if the member is currently running a task
  const currentStatus = readMemberStatus(agent.id);
  if (currentStatus === 'busy' && !input.force) {
    return `⛔ Member "${agent.friendlyName}" is currently busy. Wait for the task to complete or set force=true to remove anyway.`;
  }

  // Held check (DQ-22): the same combined reservedBy + registered-workflow-
  // package holds consult member_owner runs, so a member cannot be removed
  // out from under a live reservation or an in-progress package assignment
  // by any route other than an explicit force=true.
  if (!input.force) {
    const { refusalText } = await memberHeldCheck(agent, [agent.owner?.package ?? null]);
    if (refusalText) {
      return `\u26D4 Cannot remove member "${agent.friendlyName}": ${refusalText} Error code: member-held. Set force=true to remove anyway.`;
    }
  }

  const strategy = getStrategy(agent);
  const warnings: string[] = [];

  // Cancel any pending credential cleanup timer
  cancelCredentialCleanup(agent.id);

  // Probe a remote member once. Every member-side step below needs it, and the
  // ORDER matters: all member-side cleanup (composed config, own-install
  // registration, agy project) runs while the fleet still holds the member's
  // access, and the fleet's own access (credentials, authorized_keys) is
  // removed LAST. Local members are always reachable.
  let reachable = agent.agentType !== 'remote';
  let connectError: string | undefined;
  let connectThrew = false;
  if (agent.agentType === 'remote') {
    try {
      const conn = await strategy.testConnection();
      reachable = conn.ok;
      if (!conn.ok) connectError = conn.error ?? 'connection failed';
    } catch (e: unknown) {
      connectThrew = true;
      connectError = e instanceof Error ? e.message : String(e);
    }
  }

  // Best-effort: remove what compose_permissions wrote for this member -- the
  // per-folder apra-fleet MCP entry (?member=<id>), the fleet permission keys
  // and the git exclude lines -- so the work folder is not left pointing at a
  // member that no longer exists. Anything it could not remove is reported.
  if (reachable) {
    try {
      const removedConfig = await removeComposedMemberConfig(agent);
      logLine('remove_member', `removed composed member config (${removedConfig.join('; ') || 'nothing to remove'})`, agent);
    } catch (e: unknown) {
      warnings.push(`Could not remove the member's composed config (per-folder apra-fleet MCP entry / permission keys) from ${agent.workFolder}: ${e instanceof Error ? e.message : String(e)}`);
    }
  } else {
    warnings.push(`Member was unreachable (${connectError}) -- its composed config (per-folder apra-fleet MCP entry / permission keys) in ${agent.workFolder} was NOT removed`);
  }

  // Best-effort: drop the member's self-registration on its OWN apra-fleet
  // install (apra-fleet-b4g.56). A failure is reported, never silent.
  if (agent.agentType === 'remote') {
    try {
      const r = await removeMemberFromOwnInstall(agent, getMemberFleetMcpDeps());
      if (!r.removed && 'reason' in r) {
        warnings.push(`Could not remove the member's registration from its own apra-fleet install (${r.reason}): ${r.detail}`);
      }
    } catch (e: unknown) {
      warnings.push(`Could not remove the member's registration from its own apra-fleet install: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  // Best-effort: delete the member's agy project file (and a legacy
  // fleet-<id>.json, if present) so its permission grants don't linger on
  // its machine (docs/agy-provider.md section 1). Skipped
  // entirely when another registered member still shares the id -- deleting
  // it would strip that other member's grants too.
  if (agent.llmProvider === 'agy' && agent.agyProjectId) {
    const sharedProject = getAllAgents().some(a => a.id !== agent.id && a.agyProjectId === agent.agyProjectId);
    if (!sharedProject) {
      try {
        const result = await removeAgyProject(agent, (cmd, timeoutMs) => strategy.execCommand(cmd, timeoutMs));
        if (result.errors.length > 0) {
          warnings.push(`Could not fully remove agy project file for "${agent.friendlyName}": ${result.errors.join('; ')}`);
        }
      } catch (err) {
        warnings.push(`Could not remove agy project file for "${agent.friendlyName}": ${err instanceof Error ? err.message : String(err)}`);
      }
    }
  }

  // Best-effort: clear auth credentials from the member, and finally the
  // fleet's own SSH key. Skip for local members -- their credentials belong to
  // the host machine.
  if (agent.agentType === 'remote' && connectThrew) {
    warnings.push('Could not connect to member -- auth credentials may still be present');
  } else if (agent.agentType === 'remote') {
    try {
      if (reachable) {
        const cmds = getOsCommands(getAgentOS(agent), getAgentShell(agent));
        const exec = async (cmd: string) => {
          const r = await strategy.execCommand(cmd, 15000);
          return r.stdout;
        };
        const provider = getProvider(agent.llmProvider);

        // Remove credentials files for any provider that uses them
        const credentialFiles = provider.oauthCredentialFiles() ?? [];
        for (const file of credentialFiles) {
          await strategy.execCommand(cmds.credentialFileRemove(file.remotePath), 10000).catch(() => {});
        }

        // Remove the provider's auth env vars (every credential kind) from shell profiles
        const authVars = new Set([provider.authEnvVar, ...(provider.authEnvVarNames?.() ?? [])].filter(Boolean));
        for (const envVar of authVars) {
          for (const cmd of cmds.unsetEnv(envVar)) {
            await strategy.execCommand(cmd, 10000).catch(() => {});
          }
        }

        // VCS auth revoke: remove git credential helper if a VCS provider is configured.
        // Must pass the SAME label/scopeUrl persisted at provision time (see
        // credential-cleanup.ts) -- omitting them targets the unlabeled/
        // default-host credential-helper file/config-key pair instead of the
        // one actually deployed, leaving the real token file orphaned,
        // unrevoked, on a machine that is being decommissioned.
        if (agent.vcsProvider) {
          const vcsService = vcsProviders[agent.vcsProvider];
          if (vcsService) {
            await vcsService.revoke(agent, cmds, exec, agent.vcsCredentialLabel, agent.vcsCredentialScopeUrl).catch(() => {});
          }
        }

        // SSH key removal: remove fleet public key from remote authorized_keys
        // (fleet-generated keys only -- a user-supplied key stays authorized)
        if (agent.keyPath && isFleetManagedKey(agent.keyPath)) {
          const pubKeyPath = `${agent.keyPath}.pub`;
          try {
            const pubKey = fs.readFileSync(pubKeyPath, 'utf-8').trim();
            // Use the key type + base64 portion to match (ignore trailing comment)
            const parts = pubKey.split(/\s+/);
            const keyMatch = parts.slice(0, 2).join(' ');
            const isWindows = getAgentOS(agent) === 'windows';
            const removeKeyCmd = isWindows
              ? wrapPowerShellEncoded(`$akFile = "$env:USERPROFILE\\.ssh\\authorized_keys"; if (Test-Path $akFile) { $escaped = [regex]::Escape('${escapePowerShellArgInner(keyMatch)}'); (Get-Content $akFile) | Where-Object { $_ -notmatch $escaped } | Set-Content $akFile }`)
              // Escape for a /-delimited sed BRE, then for the single-quoted shell
              // argument (key_path is caller-supplied, so the .pub content is not
              // trusted). A well-formed key still matches the same line (types
              // with a `.`, e.g. sk-/cert keys, now carry `\.` in the pattern).
              : `sed -i '/${escapeShellArgInner(escapeSedBasicRegex(keyMatch))}/d' ~/.ssh/authorized_keys`;
            try {
              const removeKeyResult = await strategy.execCommand(removeKeyCmd, 10000);
              if (removeKeyResult.code !== 0) {
                warnings.push('Could not clear fleet public key from authorized_keys on the member');
              }
            } catch {
              warnings.push('Could not clear fleet public key from authorized_keys on the member');
            }
          } catch { /* pub key file not found — skip */ }
        }
      } else {
        warnings.push('Member was offline — could not clear auth credentials');
      }
    } catch {
      warnings.push('Could not connect to member — auth credentials may still be present');
    }
  }

  strategy.close();

  // Clean up local key files only for fleet-generated keys no other member shares
  if (agent.keyPath && isFleetManagedKey(agent.keyPath)) {
    const sharedKey = getAllAgents().some(a => a.id !== agent.id && a.keyPath === agent.keyPath);
    if (!sharedKey) {
      try { fs.unlinkSync(agent.keyPath); } catch {}
      try { fs.unlinkSync(`${agent.keyPath}.pub`); } catch {}
    }
  }

  // Clean up known_hosts entry
  if (agent.host && agent.port) {
    removeKnownHost(agent.host, agent.port);
  }

  const removed = removeFromRegistry(agent.id);
  invalidatePreflightCache(agent.id);
  getStallDetector().remove(agent.id);
  writeStatusline();

  if (removed) {
    logLine('remove_member', `id=${agent.id} name=${agent.friendlyName}`, agent);
    let result = `✅ Member "${agent.friendlyName}" (${agent.id}) has been removed.\n\nTo refresh the member list in your UI, run /mcp and select Reconnect.`;
    if (warnings.length > 0) {
      result += `\n\n⚠️ Warnings:\n`;
      for (const w of warnings) {
        result += `  - ${w}\n`;
      }
    }
    return result;
  }
  return `Failed to remove member "${agent.id}".`;
}
